module.exports.User = require('./User')
module.exports.OAuth = require('./OAuth')
module.exports.Novel = require('./Novel')
module.exports.Hashtag = require('./Hashtag')
module.exports.Episode = require('./Episode')
module.exports.Comment = require('./Comment')
module.exports.Favorites = require('./Favorites')
