const DB = require('./_DB')
const User = require('./User')
const OAuth = require('./OAuth')
const Novel = require('./Novel')
const Episode = require('./Epise')
const Comment = require('./Comment')
const Report = require('./Report')
const Hashtag = require('./Hashtag')

module.exports.User = DB.define('user', User.db, User.config)
module.exports.oAuth = DB.define('oAuth', OAuth.db, OAuth.config)
module.exports.Novel = DB.define('novel', Novel.db, OAuth.config)
module.exports.Episode = DB.define('episode', Episode.db, Episode.config)
module.exports.Comment = DB.define('comment', Comment.db, Comment.config)
module.exports.Report = DB.define('report', Report.db, Report.config)
module.exports.Hashtag = DB.define('hashtag', Hashtag.db, Hashtag.Config)
