const DB = require('./_DB')
const User = require('./User')
const OAuth = require('./OAuth')
const Novel = require('./Novel')
const Episode = require('./Epise')
const Comment = require('./Comment')
const Report = require('./Report')
const Hashtag = require('./Hashtag')

const defineTable = (name, { table, config }) => DB.define(name, table, config)

module.exports.User = defineTable('user', User)
module.exports.oAuth = defineTable('oAuth', OAuth)
module.exports.Novel = defineTable('novel', Novel)
module.exports.Episode = defineTable('episode', Episode)
module.exports.Comment = defineTable('comment', Comment)
module.exports.Report = defineTable('report', Report)
module.exports.Hashtag = defineTable('hashtag', Hashtag)
